config/routes.rb
Rails.application.routes.draw do

  root 'lemurs#index'

  resources :lemurs

end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/lemur.rb
class Lemur < ActiveRecord::Base

  scope :species, -> (species) { where species: species }
  scope :region, -> (region) { where region: region }
  scope :year, -> (year) { where year: year }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
end

app/controllers/lemurs_controller.rb
# this page under development

class LemursController < ApplicationController

# filtering_paramas will be moved down to private.  only placed here temporarily.  
	def filtering_params(params)
	  params.slice(:status, :location, :starts_with)
	end


	def index
		@lemurs = Lemur.where(nil)
	  filtering_params(params).each do |key, value|
	    @lemurs = @lemurs.public_send(key, value) if value.present?
	  end
		respond_to do |format|
			format.html
			format.xml {render xml: @lemurs}
			format.json {render json: @lemurs}
		end
	end

	def show
		@lemur = Lemur.find(params[:id])

		respond_to do |format|
			format.html
			format.xml {render xml: @lemurs}
			format.json {render json: @lemurs}
		end
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/lemurs_helper.rb
module LemursHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CaptiveLemurs</title>
  
	<link rel="points" type="application/json" href= "/MDG_adm2_3.json" />

<%= stylesheet_link_tag "//cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" %>
<%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js" %>

 <script src="https://code.jquery.com/jquery-2.1.0.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

  <script>
		$(document).ready(function(){
			initializeMap();
		});
	</script>
</head>

<body>

<%= yield %>

</body>
</html>

app/views/lemurs/_list.html.erb
<div id="filterrific_results">

  <div>
    <%= page_entries_info lemurs %>
  </div>

  <table>
    <tr>
      <th>Species</th>
      <th>Region</th>
      <th>Year</th>
    </tr>
    <% lemurs.each do |lemur| %>
      <tr>
        <td><%= link_to(lemur.species, lemur_path(@lemur)) %></td>
        <td><%= lemur.species %></td>
        <td><%= lemur.region %></td>
        <td><%= lemur.year %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= will_paginate lemurs %>

app/views/lemurs/index.html.erb
<h1> captured lemurs</h1>
<!-- 
Filters don't access map data at this time.  Will be implemented in next version.  
Need to give option for "no value included"
Values selected from the drop downs (ideally checkboxes) will used to query the map to note those regions that meet the query criteria.-->

<div class="filter_options_container">
	<h2>dropdowns to filter data</h2>
</div>

<div class="form-section">
  <form class="filter_form">
		<%= select("lemur", "species", Lemur.all.collect(&:species).uniq.sort()) %>
    <input type="submit" value="Filter" />
  </form>
	<form class="filter_form">
		<%= select("lemur", "region", Lemur.all.collect(&:region).uniq.sort()) %>
    <input type="submit" value="Filter" />
  </form>
	<form class="filter_form">
		<%= select("lemur", "year", Lemur.all.collect(&:year).uniq.sort()) %>
    <input type="submit" value="Filter" />
  </form>
</div>

<div class="instructions">
	<!-- Filtering not in place yet.   -->
	
</div>


<div id="map"></div>

app/views/lemurs/show.html.erb
<h3>Individual observation details:</h3>

<div id='individual'>

<%= @lemur.id %>
<%= @lemur.species %>
<%= @lemur.region %>
<%= @lemur.year %>
</div>
<div id='note'>
Photo will be included here if available.
</div>